### ISSUE TITLE
Is it support Azure SQL Server

### ISSUE THREAD

**Issue by zhangpengchen** [unruledboy/SQLMonitor#2]
Hi @unruledboy ,

Do you plan to support Azure SQL Server?
It will give the error "Keyword or statement option ''@@servicename" is not supported in this version of SQL Server" at this moment, and then stopped working.

Kind Regards,
ZhangPeng

**Comment by unruledboy** [comment]
Hi,

Yes, I noticed that it's not working with Azure SQL, I am planning to
support Azure, but it looks like Azure SQL has a lot of limitations,
disabling lots of internal stuffs that SQL Monitor heavily relies on.

I will have a further look shortly, as I am now developing system using
Azure SQL

**Comment by unruledboy** [comment]
@zhangpeng-kooboo  I've updated it. It now supports Azure, sorry about the delay: https://raw.githubusercontent.com/unruledboy/SQLMonitor/master/SQLMonitor.bin.zip

**Comment by zhangpengchen** [comment]
You are awesome :+1:

**Comment by unruledboy** [comment]
No worries. It is open source, if you want, you can contribute and enhance it.
